### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by john-francis96** [Esri/wind-js#22] opened 2016-08-08 09:32 UTC
dojo.io.script error
Error: Token Required.

/3.8compact/ (line 1057)

**Comment by jgravois** [comment] 2016-08-08 17:58
duplicate of #19

i *still* recommend we make `gh-pages` the default branch of this repository and get rid of `master`. if i had the keys, i'd do it myself.

**Comment by john-francis96** [comment] 2016-08-09 06:19
Using the gh-pages branch and everything works now. Thanks!

**Comment by jgravois** [comment] 2016-08-09 16:10
i've gotten the two branches in sync (manually).  sorry for the confusion.

**Closed by jgravois** 2016-08-09 16:10 UTC
